get http://localhost:8888/.netlify/functions/score-getAll
// getAll().then(function (data) {
    //   console.log(data);
// });

# create({ "name": "Ethan Haque", "score": { "accuracy": accuracy, "wpm": wpm }, "mode": { "milliseconds": milliseconds, "sentenceCount": sentenceCount } });
